### ISSUE TITLE
unused server.js

### ISSUE THREAD

**Issue by itsValyria** [annelinderaadsheer/user-experience-enhanced-website#1]
**Unused server.js**
Jij gebruikt voor jouw server/app het bestandje ```app.js```, echter heb je ook nog een ```server.js``` ongebruikt in je repo staan!

**Link naar de file**
https://github.com/annelinderaadsheer/user-experience-enhanced-website/blob/main/server.js

**Hoe los je dit op?**
Check of je het inderdaad niet nodig hebt, en als dat zo is... VERWIJDEREN DIE HANDEL!

**Bron**
C'est moi <3

**Comment by annelinderaadsheer** [comment]
Check!
