### ISSUE TITLE
De HTML elementen zijn goed gerangschikt

### ISSUE THREAD

**Issue by itsValyria** [annelinderaadsheer/user-experience-enhanced-website#3]
**De HTML elementen zijn goed gerangschikt**
Je ziet heel duidelijk dat je de elementen goed op voorbeeld gezet hebt, en dat alles goed gerangschikt is. Zo is je code fijn overzichtelijk.

**Hoe ziet dat er uit dan?!**
PS: De permalink wilde niet laden for some reason dus hier is de code die ik wilde linken:
```html
<div class="cta">
  <div class="wrapper">
    <h2>Zelf een initiatief aanmelden?</h2>
    <!-- Link naar initiatief aanmelden -->
    <a href="/opdracht" class="btn">Klik hier</a>
  </div>
</div>
```

**Comment by annelinderaadsheer** [comment]
Thanks :)
