### ISSUE TITLE
Zorg dat de generieke CSS bovenaan staat.

### ISSUE THREAD

**Issue by itsValyria** [annelinderaadsheer/user-experience-enhanced-website#4]
**Zorg dat de generieke CSS bovenaan staat.**

Je CSS is op zich best netjes, je begint met de root variables, dat is goed. Daarna heb je de styling van je menu. En daarna komen de styling van main elementen zoals h1, h2, body, p, etc.

**Je kunt het beter op deze volgorde doen:**
1. Imports (fonts bv) & :root
2. Elementen (body, main, h1, h2, ul etc)
3. Classes op volgorde van de pagina (.menu, .main-container .footerlinks bvb)

**Voorbeeld?!**
Deze code moet veeel meer naar boven!! Boven de classes.

https://github.com/annelinderaadsheer/user-experience-enhanced-website/blob/b3b87d49681b3f153609c9227efce33184c5fccf/public/style.css#L138C1-L150C2
PS: Permalink laadt nog steeds niet, rip.

**BRON?**
Bij MDN docs kun je er nog wat over lezen! :D

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Organizing

**Comment by annelinderaadsheer** [comment]
Thanks!!! :)
